// Generates supabase/migrations/0002_seed.sql from js/data.js so the browser and the database
// always agree on vehicle types and cargo categories. Run: node scripts/gen-seed.mjs
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { VEHICLE_GROUPS, VEHICLE_TYPES, CARGO_TYPES } from '../js/data.js';

const q = (s) => (s == null ? 'null' : `'${String(s).replace(/'/g, "''")}'`);
const n = (v) => (v == null ? 'null' : String(v));
const lines = [];
lines.push('-- Generated by scripts/gen-seed.mjs from js/data.js — do not edit by hand.');
lines.push('-- Vehicle types: docs/vehicle-types.json (codes as on the exchange carriers use today).');
lines.push('-- Cargo categories: PROVISIONAL set approved by the client; replace via this table, not code.');
lines.push('');
for (const g of VEHICLE_GROUPS) {
  lines.push(`insert into public.vehicle_groups (id, sort, name_lv, name_ru, name_en) values (${q(g.id)}, ${g.sort}, ${q(g.name.lv)}, ${q(g.name.ru)}, ${q(g.name.en)})`
    + ` on conflict (id) do update set sort = excluded.sort, name_lv = excluded.name_lv, name_ru = excluded.name_ru, name_en = excluded.name_en;`);
}
lines.push('');
for (const t of VEHICLE_TYPES) {
  const flags = {};
  for (const k of ['refrigerated', 'oversize', 'bulk', 'ltl']) if (t[k]) flags[k] = true;
  lines.push(`insert into public.vehicle_types (code, group_id, sort, name_lv, name_ru, name_en, tonnage_from, tonnage_to, length_m, volume_m3, flags) values (`
    + `${q(t.code)}, ${q(t.group)}, ${t.sort}, ${q(t.name.lv)}, ${q(t.name.ru)}, ${q(t.name.en)}, ${n(t.tonnage_from)}, ${n(t.tonnage_to)}, ${n(t.length_m)}, ${n(t.volume_m3)}, ${q(JSON.stringify(flags))}::jsonb)`
    + ` on conflict (code) do update set group_id = excluded.group_id, sort = excluded.sort, name_lv = excluded.name_lv, name_ru = excluded.name_ru, name_en = excluded.name_en,`
    + ` tonnage_from = excluded.tonnage_from, tonnage_to = excluded.tonnage_to, length_m = excluded.length_m, volume_m3 = excluded.volume_m3, flags = excluded.flags;`);
}
lines.push('');
for (const c of CARGO_TYPES) {
  lines.push(`insert into public.cargo_types (id, sort, name_lv, name_ru, name_en, fields, is_provisional, is_active) values (`
    + `${q(c.id)}, ${c.sort}, ${q(c.name.lv)}, ${q(c.name.ru)}, ${q(c.name.en)}, ${q(JSON.stringify(c.fields))}::jsonb, ${c.provisional ? 'true' : 'false'}, true)`
    + ` on conflict (id) do update set sort = excluded.sort, name_lv = excluded.name_lv, name_ru = excluded.name_ru, name_en = excluded.name_en, fields = excluded.fields, is_provisional = excluded.is_provisional;`);
}
lines.push('');
const out = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'supabase', 'migrations', '0002_seed.sql');
writeFileSync(out, lines.join('\n'), 'utf8');
console.log('wrote', out, VEHICLE_TYPES.length, 'vehicle types,', CARGO_TYPES.length, 'cargo types');
